General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Write a function to create and return an integer array of shape (5, 2) from a range between 100 to 200 (including 100, excluding 200) such that the difference between consecutive elements is 10.

In [ ]:
import numpy as np
def create_integer_array():
  arr=np.empty([5,2],dtype='int')
  p=range(100,200,10)
  c=-1
  for i in range(0,5):
    for j in range(0,2):
      c+=1
      arr[i][j]=p[c] 
  return(arr)

### 2
Given a numpy array ```a```, of shape ```(m, n)``` m>=3, n>=3. Write a function to return an array consisting of the elements in 3rd column of ```a``` <br>
Eg., Suppose
``` 
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]    
```
Then 
```
column_3(a) -> [3 6 9]
```

In [ ]:
def column_3(a):
  return(a[:,2])

### 3
Write a function which does the following. Given a numpy array $a$ of shape (m, n), index $i$ and an array $b$ of shape (m, ). Replace the $i_{th}$ column of $a$ with the array $b$  
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]
b = [30, 60, 90]

```    
Then,
```
replace_col(a, 2, b) -> [[1 2 30]
                         [4 5 60]
                         [7 8 90]]
```

In [ ]:
def replace_col(a, i, b):
  a[:,i]=b
  return(a)

### 4
Write a function which does the following. Given a numpy array $a$ of shape (m, n) and indices $i$, $j$. Return a numpy array which swaps the columns $i$ and $j$ of $a$
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]

swap_cols(a, 0, 2) -> [[3 2 1]
                       [6 5 4]
                       [9 8 7]]
```

In [ ]:
def swap_cols(a, i, j):
  b=[]
  b=a[:,i]
  a[:,i]=a[:,j]
  a[:,j]=b
  return a

## 5

There are various equivalent ways to define the determinant of a square matrix A, i.e. one with the same number of rows and columns. Perhaps the simplest way to express the determinant is by considering the elements in the top row and the respective minors; starting at the left, multiply the element by the minor, then subtract the product of the next element and its minor, and alternate adding and subtracting such products until all elements in the top row have been exhausted. For example, here is the result for a 4 × 4 matrix: <br>

<img src = "https://drive.google.com/uc?id=1TTljfFZAnOvqgAOiOrv6r4DDRROD-Vph"> <br>

Also, for a 2x2 matrix, this is the formula - <br>
<img src = "https://drive.google.com/uc?id=1H3aFpr1guevWjz4F-XRUQ9eP5TfjVLwu"> <br>

###5.1 Minor
Write a function that does the following. 
Given a square matrix $A$ and an index $i$, find and return the sub-matrix that is the minor corresponding to element at index $i$ of the first row of $A$

In [ ]:
def minor(A,i):
  m=[]
  c=A.shape
  for j in range(1,c[1]):
    l=[]
    for k in range(0,c[0]):
      if(k!=i):
        l.append(A[j][k])
    m.append(l)
  return(np.array(m))

###5.2
Given a square matrix $A$, write a function that computes and return the determinant using the formula given above and the helper function that you have defined called ```minor```. <br>
(Do not use the functions to compute determinant which numpy provides built in)

In [ ]:
def determinant(A):
    n=len(A)
    t=[0]*n
    total=1 
    d=1
    for i in range(0,n): 
        index=i
        while(A[index][i]==0 and index<n): 
            index+=1
        if(index==n):
            continue
        if(index!=i): 
            for j in range(0,n): 
                A[index][j],A[i][j]=A[i][j],A[index][j]   
            d=d*int(pow(-1,index-i)) 
        for j in range(0,n): 
            t[j]=A[i][j]
        for j in range(i+1,n): 
            m=t[i]
            y=A[j][i]
            for k in range(0,n):
                A[j][k]=(m*A[j][k])-(y*t[k]) 
            total=total*m
    for i in range(0,n): 
         d=d*A[i][i]
    d=int(d/total)
    return(d)