#Drill #29

<img src="https://drive.google.com/uc?id=109gQ0yPiTdJ6cBQiL1zyKiH2MD5LKTET" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1BhfG7oMzjDH685GbvW2h8b3bKhqkQeSC" width="700">


In [ ]:
import numpy as np
a = np.array([0, 1, 2, 3])
print('1-D array:', a)
print('array of numbers from 0 to 9:', np.arange(10))
print('-'*70)
b = np.array([[0, 1, 2],[3, 4, 5]])
print('2-D array:\n', b)
print('shape of b:', b.shape)
print('-'*70)
c = np.random.rand(4)
print('array with random samples:', c) 

1-D array: [0 1 2 3]
array of numbers from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
----------------------------------------------------------------------
2-D array:
 [[0 1 2]
 [3 4 5]]
shape of b: (2, 3)
----------------------------------------------------------------------
array with random samples: [0.35095179 0.13108597 0.60087773 0.39938952]


# Drill #30


<img src="https://drive.google.com/uc?id=1y7J8HlclDc_200W1oYBVtr3l-66B_2hv" width="700">

# Expected Output
<img src="https://drive.google.com/uc?id=1HPkRafcIsT7vLp8_2rR5blhjblQZJ450" width="600">

In [ ]:
a = np.identity(5)
print('5th row in the 2-d array is:', a[4, :])
a[2, 4] = 100
print(a)
print('-'*70)
b = np.arange(20)
print(b[1:18:2])
print('-'*70)
a = np.array([1, 2, 3, 4])
print(a + 1)
print(a**2)
print('-'*70)
c = np.diag([1, 2, 3, 4])
d = np.ones(4) + 1
print(c * d) 

5th row in the 2-d array is: [0. 0. 0. 0. 1.]
[[  1.   0.   0.   0.   0.]
 [  0.   1.   0.   0.   0.]
 [  0.   0.   1.   0. 100.]
 [  0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   1.]]
----------------------------------------------------------------------
[ 1  3  5  7  9 11 13 15 17]
----------------------------------------------------------------------
[2 3 4 5]
[ 1  4  9 16]
----------------------------------------------------------------------
[[2. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]


# Drill #31

<img src="https://drive.google.com/uc?id=1MEhGhXS_OC1ZisPbEGQonYcoadzvlKZZ" width="700">
<img src="https://drive.google.com/uc?id=1R24HyNqLMt8j5u3pABKpGlCDnjgUqrX9" width="1000">


# Expected Output
<img src="https://drive.google.com/uc?id=1eqiocySYtWeWuD7NV8plOjubjg0waTRC" width="700">

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 3, 5])
print(a >= b)
print(np.array_equal(a, b))
print('-'*70)
c = np.arange(1, 5)
print(np.sin(c))
print(np.log(c))
print('-'*70)
x = np.array([1, 2, 3, 4])
print(np.sum(x))
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.sum(axis=0))
print(x.sum(axis=1))
print('-'*70)
x = np.array([2, 1, 3, 0, 6, 2, 9, 7, 4, 3])
print('min value:', a.min())
print('max value:', a.max())
print('min value index:', a.argmin())
print('max value index:', a.argmax())
print('mean of x:' , x.mean())
print('median of x:',np.median(x))
print('standard deviation of x:', x.std())
print('-'*70)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
b = a.reshape((3, 2))
print(b)
print(f'shape of a is {a.shape} and shape of b is {b.shape}')
print('-'*70)
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
print(b)

[False  True  True False]
False
----------------------------------------------------------------------
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
----------------------------------------------------------------------
10
[5 7 9]
[ 6 15]
----------------------------------------------------------------------
min value: 1
max value: 4
min value index: 0
max value index: 3
mean of x: 3.7
median of x: 3.0
standard deviation of x: 2.6851443164195103
----------------------------------------------------------------------
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
shape of a is (2, 3) and shape of b is (3, 2)
----------------------------------------------------------------------
[[4 5 6]
 [2 2 3]]


##Drill #32
<img src="https://drive.google.com/uc?id=11LGUssKKIP6RSXx_fnMWMMMxrOLoLQu2" width="800">

###Expected Output
<img src="https://drive.google.com/uc?id=17R7LrG_YhIIYJKpxKjKsLm22gt4jYtHn" width="600">


In [ ]:
import numpy as np 
a1 = np.arange(1, 7).reshape(2, 3)
a2 = np.arange(1, 7).reshape(2, 3) * 10
print('a1: \n', a1, '\n a2: \n', a2) 
print('-' * 70)
a_horizontally_stacked = np.hstack([a1, a2]) 
print('Horizontal stacking: \n', a_horizontally_stacked) 
print('Shape of array after horizontal stacking: ', a_horizontally_stacked.shape) 
print('-' * 70) 
a_vertically_stacked = np.vstack([a1, a2]) 
print('Vertical stacking: \n', a_vertically_stacked) 
print('Shape of array after vertical stacking: ', a_vertically_stacked.shape) 

a1: 
 [[1 2 3]
 [4 5 6]] 
 a2: 
 [[10 20 30]
 [40 50 60]]
----------------------------------------------------------------------
Horizontal stacking: 
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]
Shape of array after horizontal stacking:  (2, 6)
----------------------------------------------------------------------
Vertical stacking: 
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
Shape of array after vertical stacking:  (4, 3)
